import type { Applicant, Prisma } from "@prisma/client";
import type {
  ApplicationPayload,
  ApplicationRecord,
  ApplicationStatus,
} from "./application-types";
import { applicantPrimaryEmail } from "./application-types";

export function applicantEmailFromPayload(payload: ApplicationPayload): string {
  return applicantPrimaryEmail(payload).trim().toLowerCase();
}

export function payloadToApplicantFields(
  payload: ApplicationPayload
): Omit<
  Prisma.ApplicantCreateInput,
  "id" | "publicId" | "status" | "currentPage" | "submittedAt"
> {
  const primary = applicantEmailFromPayload(payload);
  return {
    email: payload.email.trim() || primary,
    personalEmail: payload.personalEmail.trim() || primary,
    nationality: payload.nationality,
    countryOfResidence: payload.countryOfResidence,
    region: payload.region,
    typeOfMobility: payload.typeOfMobility,
    preferredHostInstitution: payload.preferredHostInstitution,
    proposedAcademicProgramme: payload.proposedAcademicProgramme,
    thematicArea: payload.thematicArea,
    surname: payload.surname,
    firstName: payload.firstName,
    middleName: payload.middleName ?? "",
    gender: payload.gender,
    dateOfBirth: payload.dateOfBirth,
    stateProvince: payload.stateProvince,
    homeAddress: payload.homeAddress,
    phoneNumber: payload.phoneNumber,
    linkedinUrl: payload.linkedinUrl ?? "",
    socialMediaUrl: payload.socialMediaUrl ?? "",
    passportOrIdNumber: payload.passportOrIdNumber,
    profileUploaded: payload.profileUploaded ?? false,
    passportFileName: payload.passportFileName ?? null,
    belongsToDisadvantagedGroup: payload.belongsToDisadvantagedGroup,
    disadvantagedFinancially: payload.disadvantagedFinancially,
    disadvantagedDisability: payload.disadvantagedDisability,
    disadvantagedRefugee: payload.disadvantagedRefugee,
    disadvantagedConflict: payload.disadvantagedConflict,
    disadvantagedMinority: payload.disadvantagedMinority,
    disadvantagedOther: payload.disadvantagedOther,
    disadvantagedOtherSpecify: payload.disadvantagedOtherSpecify ?? "",
    disadvantagedDocFileName: payload.disadvantagedDocFileName ?? null,
    eduBachelor: payload.eduBachelor,
    eduMaster: payload.eduMaster,
    eduPhd: payload.eduPhd,
    bachelorProgrammeUniversity: payload.bachelorProgrammeUniversity ?? "",
    bachelorCgpa: payload.bachelorCgpa ?? "",
    masterProgrammeUniversity: payload.masterProgrammeUniversity ?? "",
    masterCgpa: payload.masterCgpa ?? "",
    academicCertificatesFileName: payload.academicCertificatesFileName ?? null,
    academicTranscriptsFileName: payload.academicTranscriptsFileName ?? null,
    currentlyEnrolledInDegree: payload.currentlyEnrolledInDegree ?? "",
    registrationNumber: payload.registrationNumber ?? "",
    proofOfRegistrationFileName: payload.proofOfRegistrationFileName ?? null,
    proofOfCourseworkFileName: payload.proofOfCourseworkFileName ?? null,
    whyApplyingScholarship: payload.whyApplyingScholarship ?? "",
    cvFileName: payload.cvFileName ?? null,
    publicationsFileName: payload.publicationsFileName ?? null,
    backgroundThematicAlignment: payload.backgroundThematicAlignment ?? "",
    scholarshipCareerGoals: payload.scholarshipCareerGoals ?? "",
    africaCleanEnergyContribution: payload.africaCleanEnergyContribution ?? "",
    studyResearchPlanFileName: payload.studyResearchPlanFileName ?? null,
    researchProposalFileName: payload.researchProposalFileName ?? null,
    traineePreferredIndustrySector: payload.traineePreferredIndustrySector ?? "",
    traineeshipRelevantSkills: payload.traineeshipRelevantSkills ?? "",
    traineeshipCareerInterestArea: payload.traineeshipCareerInterestArea ?? "",
    traineeshipCurrentProgrammeType:
      payload.traineeshipCurrentProgrammeType ?? "",
    traineeshipCurrentPosition: payload.traineeshipCurrentPosition ?? "",
    staffOrganizationsWorkedWith: payload.staffOrganizationsWorkedWith ?? "",
    staffCurrentRankPosition: payload.staffCurrentRankPosition ?? "",
    staffYearsOfExperience: payload.staffYearsOfExperience ?? "",
    staffMobilityPurpose: payload.staffMobilityPurpose ?? "",
    staffProposedWorkPlan: payload.staffProposedWorkPlan ?? "",
    staffExpectedBenefits: payload.staffExpectedBenefits ?? "",
    homeInstructionLanguage: payload.homeInstructionLanguage ?? "",
    hasLanguageProficiencyCertificate:
      payload.hasLanguageProficiencyCertificate ?? "",
    languageCertificateFileName: payload.languageCertificateFileName ?? null,
    referee1Name: payload.referee1Name ?? "",
    referee1Relationship: payload.referee1Relationship ?? "",
    referee1Position: payload.referee1Position ?? "",
    referee1Institution: payload.referee1Institution ?? "",
    referee1Email: payload.referee1Email ?? "",
    referee1Phone: payload.referee1Phone ?? "",
    referee2Name: payload.referee2Name ?? "",
    referee2Relationship: payload.referee2Relationship ?? "",
    referee2Position: payload.referee2Position ?? "",
    referee2Institution: payload.referee2Institution ?? "",
    referee2Email: payload.referee2Email ?? "",
    referee2Phone: payload.referee2Phone ?? "",
    referenceLettersFileName: payload.referenceLettersFileName ?? null,
    graduateAdmissionProofFileName:
      payload.graduateAdmissionProofFileName ?? null,
    staffEmploymentProofFileName: payload.staffEmploymentProofFileName ?? null,
    staffHostCommitmentLetterFileName:
      payload.staffHostCommitmentLetterFileName ?? null,
    medicalFitnessDeclarationFileName:
      payload.medicalFitnessDeclarationFileName ?? null,
    previousIntraAfricaScholarship:
      payload.previousIntraAfricaScholarship ?? "",
    previousScholarshipDeclarationFileName:
      payload.previousScholarshipDeclarationFileName ?? null,
    declarationCertified: payload.declarationCertified ?? false,
    dataProtectionConsent: payload.dataProtectionConsent ?? false,
    applicantSignature: payload.applicantSignature ?? "",
    nextOfKinName: payload.nextOfKinName ?? "",
    nextOfKinWhatsapp: payload.nextOfKinWhatsapp ?? "",
    nextOfKinEmail: payload.nextOfKinEmail ?? "",
    nextOfKinRelationship: payload.nextOfKinRelationship ?? "",
  };
}

export function mapPrismaApplicant(row: Applicant): ApplicationRecord {
  const submittedAt = row.submittedAt ?? row.createdAt;
  return {
    id: row.publicId ?? row.id,
    status: row.status as ApplicationStatus,
    submittedAt: submittedAt.toISOString(),
    updatedAt: row.updatedAt.toISOString(),
    currentPage: row.currentPage ?? undefined,
    email: row.email,
    nationality: row.nationality,
    countryOfResidence: row.countryOfResidence,
    region: row.region,
    typeOfMobility: row.typeOfMobility,
    preferredHostInstitution: row.preferredHostInstitution,
    proposedAcademicProgramme: row.proposedAcademicProgramme,
    thematicArea: row.thematicArea,
    surname: row.surname,
    firstName: row.firstName,
    middleName: row.middleName,
    gender: row.gender,
    dateOfBirth: row.dateOfBirth,
    stateProvince: row.stateProvince,
    homeAddress: row.homeAddress,
    personalEmail: row.personalEmail,
    phoneNumber: row.phoneNumber,
    linkedinUrl: row.linkedinUrl,
    socialMediaUrl: row.socialMediaUrl,
    passportOrIdNumber: row.passportOrIdNumber,
    nextOfKinName: row.nextOfKinName,
    nextOfKinWhatsapp: row.nextOfKinWhatsapp,
    nextOfKinEmail: row.nextOfKinEmail,
    nextOfKinRelationship: row.nextOfKinRelationship,
    belongsToDisadvantagedGroup: row.belongsToDisadvantagedGroup,
    disadvantagedFinancially: row.disadvantagedFinancially,
    disadvantagedDisability: row.disadvantagedDisability,
    disadvantagedRefugee: row.disadvantagedRefugee,
    disadvantagedConflict: row.disadvantagedConflict,
    disadvantagedMinority: row.disadvantagedMinority,
    disadvantagedOther: row.disadvantagedOther,
    disadvantagedOtherSpecify: row.disadvantagedOtherSpecify,
    eduBachelor: row.eduBachelor,
    eduMaster: row.eduMaster,
    eduPhd: row.eduPhd,
    bachelorProgrammeUniversity: row.bachelorProgrammeUniversity,
    bachelorCgpa: row.bachelorCgpa,
    masterProgrammeUniversity: row.masterProgrammeUniversity,
    masterCgpa: row.masterCgpa,
    profileUploaded: row.profileUploaded,
    passportFileName: row.passportFileName,
    disadvantagedDocFileName: row.disadvantagedDocFileName,
    academicCertificatesFileName: row.academicCertificatesFileName,
    academicTranscriptsFileName: row.academicTranscriptsFileName,
    currentlyEnrolledInDegree: row.currentlyEnrolledInDegree,
    registrationNumber: row.registrationNumber,
    proofOfRegistrationFileName: row.proofOfRegistrationFileName,
    proofOfCourseworkFileName: row.proofOfCourseworkFileName,
    whyApplyingScholarship: row.whyApplyingScholarship,
    cvFileName: row.cvFileName,
    publicationsFileName: row.publicationsFileName,
    backgroundThematicAlignment: row.backgroundThematicAlignment,
    scholarshipCareerGoals: row.scholarshipCareerGoals,
    africaCleanEnergyContribution: row.africaCleanEnergyContribution,
    studyResearchPlanFileName: row.studyResearchPlanFileName,
    researchProposalFileName: row.researchProposalFileName,
    traineePreferredIndustrySector: row.traineePreferredIndustrySector,
    traineeshipRelevantSkills: row.traineeshipRelevantSkills,
    traineeshipCareerInterestArea: row.traineeshipCareerInterestArea,
    traineeshipCurrentProgrammeType: row.traineeshipCurrentProgrammeType,
    traineeshipCurrentPosition: row.traineeshipCurrentPosition,
    staffOrganizationsWorkedWith: row.staffOrganizationsWorkedWith,
    staffCurrentRankPosition: row.staffCurrentRankPosition,
    staffYearsOfExperience: row.staffYearsOfExperience,
    staffMobilityPurpose: row.staffMobilityPurpose,
    staffProposedWorkPlan: row.staffProposedWorkPlan,
    staffExpectedBenefits: row.staffExpectedBenefits,
    homeInstructionLanguage: row.homeInstructionLanguage,
    hasLanguageProficiencyCertificate: row.hasLanguageProficiencyCertificate,
    languageCertificateFileName: row.languageCertificateFileName,
    referee1Name: row.referee1Name,
    referee1Relationship: row.referee1Relationship,
    referee1Position: row.referee1Position,
    referee1Institution: row.referee1Institution,
    referee1Email: row.referee1Email,
    referee1Phone: row.referee1Phone,
    referee2Name: row.referee2Name,
    referee2Relationship: row.referee2Relationship,
    referee2Position: row.referee2Position,
    referee2Institution: row.referee2Institution,
    referee2Email: row.referee2Email,
    referee2Phone: row.referee2Phone,
    referenceLettersFileName: row.referenceLettersFileName,
    graduateAdmissionProofFileName: row.graduateAdmissionProofFileName,
    staffEmploymentProofFileName: row.staffEmploymentProofFileName,
    staffHostCommitmentLetterFileName: row.staffHostCommitmentLetterFileName,
    medicalFitnessDeclarationFileName: row.medicalFitnessDeclarationFileName,
    previousIntraAfricaScholarship: row.previousIntraAfricaScholarship,
    previousScholarshipDeclarationFileName:
      row.previousScholarshipDeclarationFileName,
    declarationCertified: row.declarationCertified,
    dataProtectionConsent: row.dataProtectionConsent,
    applicantSignature: row.applicantSignature,
  };
}
